# Generated by Django 3.2.13 on 2024-03-01 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('siglas', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
                ('href', models.CharField(max_length=200)),
                ('extract', models.TextField()),
                ('thumbnail', models.URLField()),
                ('thumbnail_width', models.FloatField()),
                ('thumbnail_height', models.FloatField()),
                ('path', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siglas', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('imagen', models.URLField()),
                ('path', models.TextField()),
                ('city', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ventana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('funcion_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cines.funcion')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cines.usuario')),
                ('ventana', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cines.ventana')),
            ],
        ),
        migrations.CreateModel(
            name='GeneroPelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=100)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cines.pelicula')),
            ],
        ),
        migrations.AddField(
            model_name='funcion',
            name='pelicula_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cines.pelicula'),
        ),
        migrations.AddField(
            model_name='funcion',
            name='sala_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cines.sala'),
        ),
        migrations.CreateModel(
            name='FormatoSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=50)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cines.sala')),
            ],
        ),
        migrations.CreateModel(
            name='ActorPelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cines.pelicula')),
            ],
        ),
    ]
