# Generated by Django 4.2.10 on 2024-02-26 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(max_length=100)),
                ('r_apellido', models.CharField(max_length=100)),
                ('r_codigo', models.CharField(max_length=100)),
                ('r_cantidad', models.IntegerField()),
                ('r_pelicula', models.CharField(max_length=100)),
                ('r_horario', models.CharField(max_length=100)),
            ],
        ),
    ]
