# Generated by Django 3.2.13 on 2024-02-26 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('href', models.CharField(max_length=200)),
                ('extract', models.TextField()),
                ('thumbnail', models.URLField()),
                ('thumbnail_width', models.FloatField()),
                ('thumbnail_height', models.FloatField()),
                ('path', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=100)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cines.pelicula')),
            ],
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cines.pelicula')),
            ],
        ),
    ]
