# Generated by Django 3.2.13 on 2024-02-29 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pelicula_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cines.pelicula')),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siglas', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('imagen', models.URLField()),
                ('path', models.TextField()),
                ('city', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ventana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Actor',
            new_name='ActorPelicula',
        ),
        migrations.RenameModel(
            old_name='Genre',
            new_name='GeneroPelicula',
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('funcion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cines.funcion')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cines.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='funcion',
            name='sala_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cines.sala'),
        ),
        migrations.AddField(
            model_name='funcion',
            name='ventana_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cines.ventana'),
        ),
    ]
