# Generated by Django 3.2.13 on 2024-02-29 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cines', '0002_auto_20240228_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(max_length=100)),
                ('r_apellido', models.CharField(max_length=100)),
                ('r_codigo', models.CharField(max_length=100)),
                ('r_cantidad', models.IntegerField()),
                ('r_pelicula', models.CharField(max_length=100)),
                ('r_horario', models.CharField(max_length=100)),
            ],
        ),
    ]
