# Generated by Django 3.2.13 on 2024-02-26 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cines', '0002_actor_genre_pelicula'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Actor',
            new_name='ActorPelicula',
        ),
        migrations.RenameModel(
            old_name='Genre',
            new_name='GeneroPelicula',
        ),
    ]
