# Generated by Django 3.2.13 on 2024-02-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cines', '0003_auto_20240225_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siglas', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('imagen', models.URLField()),
                ('path', models.TextField()),
            ],
        ),
    ]
