# Generated by Django 3.2.13 on 2024-02-29 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cines', '0003_reserva2'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormatoSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=50)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cines.sala')),
            ],
        ),
    ]
